- name: Enable Redis 7
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: 0.0.0.0

- name: protected mode off
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "protected-mode"
    line: "protected-mode no"

- name: Enable and Start Redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes