[mongodb]
mongodb-dev.rajeshirrinki.online

[catalogue]
catalogue-dev.rajeshirrinki.online

[redis]
redis-dev.rajeshirrinki.online

[user]
user-dev.rajeshirrinki.online

[cart]
cart-dev.rajeshirrinki.online

[mysql]
mysql-dev.rajeshirrinki.online

[shipping]
shipping-dev.rajeshirrinki.online

[rabbitmq]
rabbitmq-dev.rajeshirrinki.online

[payment]
payment-dev.rajeshirrinki.online

[frontend]
frontend-dev.rajeshirrinki.online

[local]
localhost