- name: Import Nodejs setup
  ansible.builtin.import_role: 
    name: common
    tasks_from: nodejs_setup.yaml

- name: Copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check data status
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: INDEX

- name: Load master data
  ansible.builtin.command : mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js 
  when: INDEX.stdout | int < 0
  notify: Restart catalogue