- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Maven build
  ansible.builtin.shell: mvn clean package 
  args:
    chdir: /app

- name: Rename Package
  ansible.builtin.copy:
    src: /app/target/shipping-1.0.jar
    dest: /app/shipping.jar
    remote_src: true

