- name: Installing packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python3 
  - gcc 
  - python3-devel

- name: User creation
  ansible.builtin.user:
    name: roboshop
    home: /app
    shell: /sbin/nologin
    system: yes

- name: Removing existing app directort=y
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: roboshop

- name: Removing existing zip file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Downloading {{ component }} code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
    dest: /tmp/{{ component }}.zip

- name: Unarchive {{ component }} code
  ansible.builtin.unarchive:
    src:  /tmp/{{ component }}.zip
    dest: /app
    remote_src: true

- name: Install dependencies  
  ansible.builtin.pip:
    requirements: /app/requirements.txt



 